name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_mysql, bcmath, pcntl
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ---- CI-only .env (does NOT touch Forge or your local .env) ----
      - name: Copy env (CI MySQL)
        run: |
          cp .env.example .env
          # ensure APP_KEY is empty so artisan can set it
          sed -i 's/^APP_KEY=.*/APP_KEY=/' .env || true

          {
            echo "DB_CONNECTION=mysql"
            echo "DB_HOST=127.0.0.1"
            echo "DB_PORT=3306"
            echo "DB_DATABASE=testing"
            echo "DB_USERNAME=root"
            echo "DB_PASSWORD=root"
          } >> .env

          # sanity check
          echo "::group::.env (tail)"
          tail -n 20 .env
          echo "::endgroup::"

      - name: Composer install
        run: composer install --no-interaction --prefer-dist

      - name: Generate key & migrate
        run: |
          php artisan key:generate
          php artisan migrate --force

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress --error-format=github

      - name: Pint (lint)
        run: vendor/bin/pint --test

      - name: NPM install + build
        run: |
          npm ci
          npm run build

      - name: PHPUnit
        run: php artisan test --parallel --recreate-databases
